services:
  mysql-backup:
    image: latzzo/mysql-backup-runner:test
    env_file:
      - .env.db
    environment:
      - SSH_PRIVATE_KEY_NAME=id_isac
    networks:
      - betty_network
    volumes:
      - ~/.ssh:/root/.ssh/:ro
      - ./logs:/var/log
      - ./backups:/backup
    restart: "no"

networks:
  betty_network:
    external: true